export const FETCH_USER = 'fetch_user';
export const CREATE_PRODUCT = 'create_product';
export const FETCH_ALL_PRODUCTS = 'fetch_all_products';
export const DELETE_PRODUCT = 'delete_product';
export const UPDATE_PRODUCT = 'update_product';
export const FETCH_USER_PRODUCTS = 'fetch_user_products';
export const FETCH_SEARCH_RESULT = 'fetch_search_result';
export const CREATE_CHAT_ROOM = 'create_chat_room';
// export const FETCH_PRODUCT_BY_ID = 'fetch_product_by_id';